packages:
  - 'apps/*'
allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': set this to true or false
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: set this to true or false
  oracledb: true
  prisma: true
  protobufjs: true
patchedDependencies:
  react-native-gesture-handler: patches/react-native-gesture-handler.patch
  react-native-screens: patches/react-native-screens.patch
